apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: springboot
  app: spring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring
  template:
    metadata:
      labels:
        app: spring
    spec:
      containers:
      - image: kartikrj/spring-boot-mongo
        name: springboot
        ports:
        - name: springboot
          containerPort: 8080      


