apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot
  labels:
    app: spring-boot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-boot
  template: 
    metadata: 
      labels: 
        app: spring-boot 
    spec:
      containers:
        - name: spring-boot
          image: kartikrj/spring-boot-mongo
          ports:
            - containerPort: 8090

---
apiVersion: v1
kind: Service
metadata:
  name: spring-boot
spec:
  type: LoadBalancer
  selector:
    app: spring-boot
  ports:
    - port: 8090
      targetPort: 30022


